Repository ItsRauf/esmcord, pull requests merged in 2021-05, with the labels that each got.

#10 feat(Message): add message methods
  src/classes/Message.ts
Labels: enhancement

#11 feat(GuildMember): create guild member class
  .github/workflows/codeql-analysis.yml
  src/classes/Base.ts
  src/classes/BaseChannel.ts
  src/classes/BaseUser.ts
  src/classes/ClientUser.ts
  src/classes/DMChannel.ts
  src/classes/Guild.ts
  src/classes/GuildMember.ts
  src/classes/GuildText.ts
  src/classes/Message.ts
  src/classes/UnavailableGuild.ts
  src/classes/User.ts
Labels: enhancement

#12 feat(Message): add guild and editable props
  src/classes/Message.ts
Labels: enhancement

#13 Typo Fixes
  .github/workflows/main.yml
  README.md
  docs/classes/classes_base.base.html
  docs/classes/classes_basechannel.basechannel.html
  docs/classes/classes_baseuser.baseuser.html
  docs/classes/classes_clientuser.clientuser.html
  docs/classes/classes_dmchannel.dmchannel.html
  docs/classes/classes_guild.guild.html
  docs/classes/classes_guildmember.guildmember.html
  docs/classes/classes_guildtext.guildtext.html
  docs/classes/classes_message.message.html
  docs/classes/classes_messageablechannel.messageablechannel.html
  docs/classes/classes_snowflake.snowflake.html
  docs/classes/classes_unavailableguild.unavailableguild.html
  docs/classes/classes_user.user.html
  docs/classes/client.client-1.html
  docs/classes/helpers_logger.logger.html
  docs/classes/stores_basestore.basestore.html
  docs/classes/stores_channelstore.channelstore.html
  docs/classes/stores_directmessagestore.directmessagestore.html
  docs/classes/stores_guildstore.guildstore.html
  docs/classes/stores_messagestore.messagestore.html
  docs/interfaces/classes_clientuser.clientuserdata.html
  docs/interfaces/classes_guildtext.guildtextdata.html
  docs/interfaces/client.clientevents.html
  docs/interfaces/client.clientoptions.html
  docs/modules/classes_messageablechannel.html
  docs/modules/events_guild_create.html
  docs/modules/events_message_create.html
  docs/modules/events_ready.html
  docs/modules/helpers_httprequest.html
  docs/modules/helpers_proxysettoedit.html
  package.json
Labels: documentation

#14 fix(readme): fix the example to actually work
  README.md
Labels: documentation

#20 GuildMemberStore#search
  src/stores/GuildMemberStore.ts
Labels: enhancement

#22 stuff
  package.json
  src/Client.ts
Labels: enhancement

#23 revert back to 4.2.x cuz typedoc
  package.json
  pnpm-lock.yaml
Labels: bug

#24 feat: Guild Bans and Kicks
  src/Client.ts
  src/classes/Guild.ts
  src/classes/GuildBan.ts
  src/classes/GuildMember.ts
  src/events/GUILD_BAN_ADD.ts
  src/events/GUILD_BAN_REMOVE.ts
  src/stores/GuildBanStore.ts
Labels: enhancement

#25 feat(Events): GuildMemberAdd, GuildMemberRemove, GuildMemberUpdate
  src/Client.ts
  src/classes/GuildMember.ts
  src/events/GUILD_MEMBER_ADD.ts
  src/events/GUILD_MEMBER_REMOVE.ts
  src/events/GUILD_MEMBER_UPDATE.ts
Labels: enhancement
